apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: afle0qfxs-go-gitops
  description: This is GitOps manifest for afle0qfxs-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=afle0qfxs-go
    backstage.io/kubernetes-id: afle0qfxs-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: afle0qfxs-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:afle0qfxs-go
