apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: afle0qfxs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: afle0qfxs-go 
  name: afle0qfxs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: afle0qfxs-go 
